### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by Brugman** [Brugman/overwatch-counters#10]
Getting the CSV from Google takes most of the page load.

**Comment by bosconian-dynamics** [comment]
Sadly I don't see anything obvious in the response headers that could be used to make a quick `HEAD` check to see if the spreadsheet's changed ☹️

**Comment by Brugman** [comment]
That would've been a very clever method. I was thinking to just cache the data and write a new url/file to call if you want to update the cache.
